title: Marco Rovell
baseurl: "" # the subpath of the site
url: "https://marcorovell.github.io" # the base hostname & protocol for the site

permalink: pretty
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag 