title: My GitHub Page
description: A personal website hosted on GitHub Pages
baseurl: "" # the subpath of the site
url: "https://marcorovell.github.io" # the base hostname & protocol for the site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag 